"""initial
Revision ID: 574b48de7632
Revises:
Create Date: 2025-12-12 00:46:59.216106
"""
from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision = "574b48de7632"
down_revision = None
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('name', sa.VARCHAR(length=200), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('application_history',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('application_id', sa.INTEGER(), nullable=False),
        sa.Column('from_stage', sa.VARCHAR(length=9), nullable=True),
        sa.Column('to_stage', sa.VARCHAR(length=9), nullable=True),
        sa.Column('changed_by', sa.INTEGER(), nullable=True),
        sa.Column('notes', sa.TEXT(), nullable=True),
        sa.Column('created_at', sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
        sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_history_id'), 'application_history', ['id'], unique=False)
    op.create_table('users',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('email', sa.VARCHAR(length=200), nullable=False),
        sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
        sa.Column('full_name', sa.VARCHAR(length=200), nullable=True),
        sa.Column('role', sa.VARCHAR(length=14), nullable=False),
        sa.Column('company_id', sa.INTEGER(), nullable=True),
        sa.Column('created_at', sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    op.create_table('jobs',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('company_id', sa.INTEGER(), nullable=False),
        sa.Column('title', sa.VARCHAR(length=200), nullable=False),
        sa.Column('description', sa.TEXT(), nullable=True),
        sa.Column('status', sa.VARCHAR(length=6), nullable=True),
        sa.Column('created_at', sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_table('applications',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('user_id', sa.INTEGER(), nullable=False),
        sa.Column('job_id', sa.INTEGER(), nullable=False),
        sa.Column('stage', sa.VARCHAR(length=9), nullable=True),
        sa.Column('resume_url', sa.VARCHAR(), nullable=True),
        sa.Column('created_at', sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop in reverse order
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_application_history_id'), table_name='application_history')
    op.drop_table('application_history')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
